### ISSUE TITLE
ValueError: MirrorTransform now takes the axes as the spatial dimensions.

### ISSUE THREAD

**Issue by bahetibhakti** [SimonKohl/probabilistic_unet#2]
I installed all the required dependancies and tried hard to run the code but stuck at following error. Please help

Reading from /home/gpu3/prob_unet/output/quarter/train/stuttgart
Reading from /home/gpu3/prob_unet/output/quarter/train/weimar
Reading from /home/gpu3/prob_unet/output/quarter/train/jena
Reading from /home/gpu3/prob_unet/output/quarter/train/aachen
Reading from /home/gpu3/prob_unet/output/quarter/train/bochum
Reading from /home/gpu3/prob_unet/output/quarter/train/hanover
Reading from /home/gpu3/prob_unet/output/quarter/train/tubingen
Reading from /home/gpu3/prob_unet/output/quarter/train/erfurt
Reading from /home/gpu3/prob_unet/output/quarter/train/bremen
Reading from /home/gpu3/prob_unet/output/quarter/train/zurich
Reading from /home/gpu3/prob_unet/output/quarter/train/hamburg
Reading from /home/gpu3/prob_unet/output/quarter/train/dusseldorf
Reading from /home/gpu3/prob_unet/output/quarter/train/cologne
Reading from /home/gpu3/prob_unet/output/quarter/train/strasbourg
Reading from /home/gpu3/prob_unet/output/quarter/train/krefeld
train set comprises 2701 files.
Traceback (most recent call last):
  File "train_prob_unet.py", line 188, in <module>
    train(cf)
  File "train_prob_unet.py", line 39, in train
    data_provider = get_train_generators(cf)
  File "/home/gpu3/probabilistic_unet/training/data/cityscapes/data_loader.py", line 335, in get_train_generators
    n_batches=cf.n_train_batches)
  File "/home/gpu3/probabilistic_unet/training/data/cityscapes/data_loader.py", line 300, in create_data_gen_pipeline
    mirror_transform = MirrorTransform(axes=(3,))
  File "/home/gpu3/probabilistic_unet/training/batchgenerators/transforms/spatial_transforms.py", line 192, in __init__
    raise ValueError("MirrorTransform now takes the axes as the spatial dimensions. What previously was "
ValueError: MirrorTransform now takes the axes as the spatial dimensions. What previously was axes=(2, 3, 4) to mirror along all spatial dimensions of a 5d tensor (b, c, x, y, z) is now axes=(0, 1, 2). Please adapt your scripts accordingly.

**Comment by BrianDo2005** [comment]
Hi @bahetibhakti 
Have you found out the solution for the above error? I encounter the same error.

**Comment by hajtos** [comment]
I know that this is a bit late for an answer, but replacing line 300 from file `probabilistic_unet/training/data/cityscapes/data_loader.py` from:
`mirror_transform = MirrorTransform(axes=(3,))`
to:
`mirror_transform = MirrorTransform(axes=(1,))`
fixes the issue
